#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-coloredlogs
Version  : 15.0.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/cc/c7/eed8f27100517e8c0e6b923d5f0845d0cb99763da6fdee00478f91db7325/coloredlogs-15.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/cc/c7/eed8f27100517e8c0e6b923d5f0845d0cb99763da6fdee00478f91db7325/coloredlogs-15.0.1.tar.gz
Summary  : Colored terminal output for Python's logging module
Group    : Development/Tools
License  : MIT
Requires: pypi-coloredlogs-bin = %{version}-%{release}
Requires: pypi-coloredlogs-license = %{version}-%{release}
Requires: pypi-coloredlogs-python = %{version}-%{release}
Requires: pypi-coloredlogs-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(capturer)
BuildRequires : pypi(humanfriendly)
BuildRequires : pypi(pytest)
BuildRequires : pypi(pytest_cov)
BuildRequires : pypi(verboselogs)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
================================================================

%package bin
Summary: bin components for the pypi-coloredlogs package.
Group: Binaries
Requires: pypi-coloredlogs-license = %{version}-%{release}

%description bin
bin components for the pypi-coloredlogs package.


%package license
Summary: license components for the pypi-coloredlogs package.
Group: Default

%description license
license components for the pypi-coloredlogs package.


%package python
Summary: python components for the pypi-coloredlogs package.
Group: Default
Requires: pypi-coloredlogs-python3 = %{version}-%{release}

%description python
python components for the pypi-coloredlogs package.


%package python3
Summary: python3 components for the pypi-coloredlogs package.
Group: Default
Requires: python3-core
Provides: pypi(coloredlogs)
Requires: pypi(humanfriendly)

%description python3
python3 components for the pypi-coloredlogs package.


%prep
%setup -q -n coloredlogs-15.0.1
cd %{_builddir}/coloredlogs-15.0.1
pushd ..
cp -a coloredlogs-15.0.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678995231
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-coloredlogs
cp %{_builddir}/coloredlogs-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-coloredlogs/4533bebc7b149028bc2932234fc49ca4d1a61d07 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/coloredlogs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-coloredlogs/4533bebc7b149028bc2932234fc49ca4d1a61d07

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
